spring:
  application:
    name: football-aggregator

  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/footballdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

api:
  football:
    key: 06e571bd5191cfbedbd3993c2f3318dc
    url: https://v3.football.api-sports.io