# =====================
# APP NAME
# =====================
spring.application.name=football-aggregator

  # =====================
  # DATABASE (PostgreSQL)
  # =====================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

  # =====================
  # JPA / HIBERNATE
  # =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

  # =====================
  # REDIS
  # =====================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

  # =====================
  # RABBITMQ
  # =====================
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

  # =====================
  # SERVER
  # =====================
server.port=${PORT:8080}

  # =====================
  # FOOTBALL API
  # =====================
api.football.key=${API_FOOTBALL_KEY}
api.football.url=https://v3.football.api-sports.io